### PR TITLE
feat: Update plugin-functions from 1.14.4 to 1.16.0

### PR DESCRIPTION
**Pull request by edmorley**
This includes:
- Java + Node template update to default to Salesforce API 56.0
- Java local function runner runtime update from v1.0.7 to v1.1.2
- Java template fix for Java SDK 1.1
- Initial (alpha) support for Python Functions (hidden by default for now)

Full changes:
https://github.com/salesforcecli/plugin-functions/compare/1.14.4...1.16.0
https://github.com/heroku/sf-functions-core/compare/v0.4.3...v0.5.0

In addition, `@salesforce/ts-sinon` had to be added to `devDependencies`, since this repository depends on the package but previously didn't have it as an explicit dependency. This resulted in failures with the new `plugin-functions` version, since it recently moved `@salesforce/ts-sinon` from `dependencies` to `devDependencies`, in:
https://github.com/salesforcecli/plugin-functions/commit/e4e36cdd3337739ddf5574eba42f4e6c71f629c7

[@W-11790647@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000016vVRqYAM/view)

### CODE REVIEW

**Review by cristiand391 — APPROVED** [review]

**Comment by edmorley** [comment]
Thank you for the review!

**Comment by edmorley** [comment]
@cristiand391 I don't suppose there is any way to get this into tomorrow's scheduled release? Product are keen to try out the Python Functions support (and for the docs/devrel teams to be able to start using it) :-)

**Comment by RodEsp** [comment]
Heya @edmorley, now that it's been merged into `main` it will automatically be included in tomorrow's `stable-rc` release (`latest-rc` on npm). `stable-rc` will be promoted to `stable` next Wednesday (`latest` on npm). 

Users can switch to `stable-rc` running `sfdx update stable-rc` (or `npm install @salesforce/cli@latest-rc -g` for npm installs).

**Comment by edmorley** [comment]
Thank you :-)

**Comment by cromwellryan** [comment]
Let's go! 🐍

**Comment by edmorley** [comment]
@RodEsp Now that the #444 PR has been merged, and the GitHub Actions release workflow completed, I see that NPM is reporting 1.57.0 under the `latest-rc` tag on NPM:
https://www.npmjs.com/package/@salesforce/cli?activeTab=versions

I ran `sfdx update stable-rc`, which output:

```
$ sfdx update stable-rc
sfdx-cli: Updating sf... done
# Release notes for 'sfdx':

## 7.179.0 (Dec 1, 2022) [stable-rc]

<SNIP>

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


user plugins are
$
```

However, after that the version of `sf` was still `1.56.0`:

```
$ sf --version
@salesforce/cli/1.56.0 darwin-x64 node-v18.12.1
```

I then ran update against `sf` itself, and not `sfdx`, like so:

```
$ sf update stable-rc
 ›   Warning: Running "sf update" has no effect because you're using a version of sf that was installed by sfdx. To update sf, run "sfdx update".
@salesforce/cli: Updating CLI from 1.56.0-3def40b to 1.57.0-3538ca4 (stable-rc)... done
```

Though, as the warning said, that didn't have any effect:

```
$ sf --version
@salesforce/cli/1.56.0 darwin-x64 node-v18.12.1
```

Does the CLI 1.57.0 RC release just need to propagate into a new`sfdx` release, which is yet to come, but scheduled for later? 
Also, I don't suppose there are any docs about this, so I can stop pestering you with questions? :-)

**Comment by RodEsp** [comment]
@edmorley oh, I'm sorry! I misspoke up above.

`sfdx`'s `latest-rc` doesn't go out until tomorrow (every Thursday), so even though `sf`'s is out (every Wednesday) it won't be packaged and released with `sfdx`'s until tomorrow.

There are unfortunately no docs on the CLI's release schedules but we are working on consolidating both CLI's and their release process so soon their releases will happen at the exact same time and there won't be any need to explain that.

**Comment by edmorley** [comment]
Ah I see https://github.com/salesforcecli/sfdx-cli/pull/789 now, thank you.

**Pull request merged**
